services:
  modelab_db:
    image: mysql:8.0
    container_name: modelab_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: "exit 0"
  
  modelab:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_PATH: ${VITE_API_PATH}
        VITE_CLIENT_ID: ${VITE_CLIENT_ID}
        VITE_DEV_LOGIN: ${VITE_DEV_LOGIN}
    container_name: modelab
    restart: unless-stopped
    ports:
      - "8030:80"
    env_file:
      - .env
    depends_on:
      modelab_db:
        condition: service_healthy