services:
  modelab_db:
    image: mysql:8.0
    container_name: modelab_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # Only if you need to access DB manually
    # ports:
    #   - "3307:3306"
    healthcheck:
      test: "exit 0"
  
  modelab:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_CLIENT_ID: ${VITE_CLIENT_ID}
        DEV_MODE: ${DEV_MODE}
        DATA_MAX_SIZE_MB: ${DATA_MAX_SIZE_MB}
        DB_SERVERNAME: ${DB_SERVERNAME}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_DATABASE: ${DB_DATABASE}
    container_name: modelab
    restart: unless-stopped
    ports:
      - "${HOSTED_PORT}:80"
    env_file:
      - .env
    depends_on:
      modelab_db:
        condition: service_healthy